### ISSUE TITLE
Error when reading in concrete sections 

### ISSUE THREAD

**Issue by Adamek2192** [BHoM/MidasCivil_Toolkit#198]
Description:
Error when reading in concrete sections. 1. No Source information is available for the dataset named Materials\MaterialsUSA\Concrete

#### Steps to reproduce:
1. This component failed to run properly.
- Error: Unable to cast object of type 'BH.oM.Structure.SectionProperties.GenericSection' to type 'BH.oM.Structure.SectionProperties.SteelSection'.
- Occured in  BH.Engine.MidasCivil.Convert.ToBar(String bar, Dictionary`2 bhomNodes, Dictionary`2 bhomSectionProperties, Dictionary`2 bhomMaterials, Dictionary`2 barReleases, Dictionary`2 barReleaseAssignments)
     called from BH.Adapter.MidasCivil.MidasCivilAdapter.ReadBars(List`1 ids)
- Are you sure you have the correct type of inputs? Check their description for more details.

**Comment by peterjamesnugent** [comment]
This warning has been fixed in this Pull Request: https://github.com/BHoM/BHoM_Datasets/pull/29
> Error when reading in concrete sections. 1. No Source information is available for the dataset named Materials\MaterialsUSA\Concrete 

I'll revamp how we read in Sections in MidasCivil - there's a bit of legacy code in there that can be stripped out. 
> Occured in BH.Engine.MidasCivil.Convert.ToBar(String bar, Dictionary2 bhomNodes, Dictionary2 bhomSectionProperties, Dictionary2 bhomMaterials, Dictionary2 barReleases, Dictionary2 barReleaseAssignments) called from BH.Adapter.MidasCivil.MidasCivilAdapter.ReadBars(List1 ids)

1. ReadSectionProperties will read everything as a GenericSection
2. ReadBars will read Materials and SectionProperties
3. Before converting to a Bar, create a list of Material and SectionProperty combinations
4. At this stage the correct (Concrete/Steel etc.) Section is created
5. Feed this in to Convert.ToBar() so it is not handled on a Bar level creating duplicate SectionProperty objects
